import { CheerioAPI } from 'cheerio';
import { BaseSniffer } from './base';
import { SniffResult } from '../types';

/**
 * Detects AI-generated placeholder comments and TODOs in HTML
 */
export class CommentsSniffer extends BaseSniffer {
  constructor() {
    super('Comments');
  }

  sniff(cheerio: CheerioAPI): SniffResult {
    let score = 0;
    const messages: string[] = [];
    const foundComments: string[] = [];

    // Get the raw HTML to extract comments
    const html = cheerio.html();

    // Extract HTML comments
    const commentRegex = /<!--([\s\S]*?)-->/g;
    let match;
    let todoCount = 0;
    let aiPlaceholderCount = 0;

    while ((match = commentRegex.exec(html)) !== null) {
      const comment = match[1].trim();

      // Check for TODO comments (very common in AI-generated code)
      if (/TODO:/i.test(comment)) {
        todoCount++;
        foundComments.push(comment.substring(0, 60));
      }

      // Check for AI placeholder comments
      if (/update|change|replace|set|add your|customize|modify/i.test(comment)) {
        aiPlaceholderCount++;
      }

      // Check for specific AI builder signatures
      if (/lovable|v0\.dev|bolt\.new|cursor|generated by ai/i.test(comment)) {
        score += 0.8;
        messages.push(`AI builder signature found in comment: "${comment.substring(0, 50)}..."`);
      }
    }

    if (todoCount >= 3) {
      score += 0.8;
      messages.push(`${todoCount} TODO comments found (AI-generated boilerplate)`);
    } else if (todoCount >= 1) {
      score += 0.5;
      messages.push(`${todoCount} TODO comment(s) in production code (likely AI-generated)`);
    }

    if (aiPlaceholderCount >= 2) {
      score += 0.6;
      messages.push(`${aiPlaceholderCount} placeholder comments suggesting unfinished AI template`);
    }

    // Check for Lovable-specific badge in HTML
    if (html.includes('lovable-badge') || html.includes('Built with Lovable')) {
      score += 1.0;
      messages.push('Lovable AI builder badge detected');
    }

    // Check for v0.dev signatures
    if (html.includes('v0.dev') || html.includes('Generated by v0')) {
      score += 1.0;
      messages.push('v0.dev AI builder detected');
    }

    // Check for Bolt.new signatures
    if (html.includes('bolt.new') || html.includes('StackBlitz')) {
      score += 0.9;
      messages.push('Bolt.new/StackBlitz AI builder detected');
    }

    score = Math.min(score, 1.0);

    if (messages.length === 0) {
      return this.createResult(0, 'No AI-generated comments or placeholders found');
    }

    return this.createResult(parseFloat(score.toFixed(2)), messages.join('; '));
  }
}
